name: diff-cloth
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib==3.4.3  
  - ipykernel
  - pip==22.3.1
  - python==3.9.16
  - pip:
    - scipy==1.10.0
    - numpy==1.24.2
    - jax==0.3.1
    - jaxlib==0.3.0
